FROM deployit_web:latest

USER root

# Remove useless services
RUN rm -rf /etc/service/nginx
RUN rm -rf /etc/service/puma

# Create services directories
RUN mkdir -p /etc/service/sidekiq

# Copy start scripts
ADD conf/runit/start-sidekiq.sh /etc/service/sidekiq/run
RUN chmod +x /etc/service/*/run
