FROM deployit_web:latest
MAINTAINER Nicolas Rodriguez "nrodriguez@jbox-web.com"

USER root

# Remove useless services
RUN rm -rf /etc/service/nginx
RUN rm -rf /etc/service/puma
RUN rm -rf /etc/service/faye

# Create services directories
RUN mkdir -p /etc/service/ssh

# Copy start scripts
ADD conf/runit/start-ssh.sh /etc/service/ssh/run
RUN chmod +x /etc/service/*/run

EXPOSE 22
