FROM deployit_web:latest

USER root

# Remove useless services
RUN rm -rf /etc/service/nginx
RUN rm -rf /etc/service/puma

# Create services directories
RUN mkdir -p /etc/service/ssh

# Copy start scripts
ADD conf/runit/start-ssh.sh /etc/service/ssh/run
RUN chmod +x /etc/service/*/run

EXPOSE 22
